name: markdown-from-json

on: [push]

jobs:        
  auto-update-readme:
      runs-on: ubuntu-latest
      steps:
        - name: Checkout
          uses: actions/checkout@v2
        - name: Order objects by a given property from a json file 
          uses: aloisdg/order-by-json@v0.1
          with:
            # Optional output file paths, defaults to '[./README.md]'.
            input-path: data/organizations.json
            output-path: data/organizations.json
            property: Abbreviation

        - name: setup git config
          run: |
            # setup the username and email. I tend to use 'GitHub Actions Bot' with no email by default
            git config user.name "d-edge-bot"
            git config user.email "<>"

        - name: commit
          run: |
            # Stage the file, commit and push
            git add data/organizations.json
            git commit -m "order json"
            git push origin main

        - name: Markdown autodocs
          uses: dineshsonachalam/markdown-autodocs@v1.0.3
          with:
            # Optional output file paths, defaults to '[./README.md]'.
            output_file_paths: '[./README.md]'

            # Categories to automatically sync or transform its contents in the markdown files.
            # Defaults to '[code-block,json-to-html-table,workflow-artifact-table]'
            categories: 'json-to-html-table'
