name: markdown-from-json

on: [push]

jobs:        
  auto-update-readme:
      runs-on: ubuntu-latest
      steps:
        - uses: actions/checkout@v2
        - name: Order objects by a given property from a json file 
          uses: aloisdg/order-by-json@v1.0.0
          with:
            # Optional output file paths, defaults to '[./README.md]'.
            input-path: data/organizations.json
            output-path: data/organizations.json
            property: Abbreviation
        - name: Markdown autodocs
          uses: dineshsonachalam/markdown-autodocs@v1.0.3
          with:
            # Optional output file paths, defaults to '[./README.md]'.
            output_file_paths: '[./README.md]'

            # Categories to automatically sync or transform its contents in the markdown files.
            # Defaults to '[code-block,json-to-html-table,workflow-artifact-table]'
            categories: 'json-to-html-table'
